<?php
session_start();
include("conexao_new.php");
?>
<!DOCTYPE>
<!-- NewPage -->
<html lang="pt">
<head>
<!-- Generated by javadoc (version 1.7.0_51) on Fri Apr 17 22:20:24 BRT 2015 -->
<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
<title>Dashboard</title>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.2/css/bootstrap.min.css" rel="stylesheet">  
<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet">  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
</script>
<script>
// $("#cad option[value=2]").attr('selected', 'selected');
</script>
<style type="text/css" >
	.container {
  padding: 2rem 0rem;
}

h4 {
  margin: 2rem 0rem 1rem;
}

.table-image {
  td, th {
    vertical-align: middle;
  }
}

</style>
</head>
<body>
<?php
if($_GET){
if (isset($_GET['id'])) {
    $id =  $_GET['id'];
    $op =  $_GET['op'];
    $sql;
    if($op==1){
      $sql = "update reconhecimento set ativo = 1 where id = $id;";
      $result = mysql_query($sql) or die(mysql_error());
      

    }else if($op == 2){
      $sql = "update reconhecimento set ativo = 2 where id = $id;";
      $result = mysql_query($sql) or die(mysql_error());
    }

    if(mysql_query($sql)){
    	?>
                <script>
                   alert("Alterações realizadas com sucesso!");
                   </script>
                <?php
    }else{
    	?>
                <script>
                   alert("Erro ao realizar alterações!");
                   </script>
                <?php
    }

      }
}



?>
<div class="container">
	<div class="row">
		
            <div class="input-group">
               <select id="cad" name="cad" class="form-control"> 
                    
                    <option value="1">Pendentes</option>
                    <option value="2">Aprovados</option>
                    <option value="3">Recusados</option>
                     
                </select>
                      <span class="input-group-append">
                          <button id="pesquisarButton" type="button" class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </span>
            </div>
	</div>
  <div class="row">
    <div class="col-12">
		<table class="table table-image">
		  <thead>
		    <tr>
		      <th scope="col">Image</th>
		      <th scope="col">Nome</th>
		      <th scope="col">Identificação</th>
		      <th scope="col">Ações</th>
		    </tr>
		  </thead>
		  <tbody>


<?php
$sql = "select r.id, r.rg_aluno, r.cpf, r.imagem, r.ativo, r.tracker, u.NOME_ALUNO from reconhecimento as r inner join unijui as u on u.matr_aluno = r.rg_aluno where r.ativo = 0 group by u.NOME_ALUNO ;";
if (isset($_GET['filter'])) {
	if($_GET['filter']==1){
		$sql = "select r.id, r.rg_aluno, r.cpf, r.imagem, r.ativo, r.tracker, u.NOME_ALUNO from reconhecimento as r inner join unijui as u on u.matr_aluno = r.rg_aluno where r.ativo = 0 group by u.NOME_ALUNO ;";
	}else if($_GET['filter']==2){
		$sql = "select r.id, r.rg_aluno, r.cpf, r.imagem, r.ativo, r.tracker, u.NOME_ALUNO from reconhecimento as r inner join unijui as u on u.matr_aluno = r.rg_aluno where r.ativo = 1 group by u.NOME_ALUNO ;";
	}else if($_GET['filter']==3){
		$sql = "select r.id, r.rg_aluno, r.cpf, r.imagem, r.ativo, r.tracker, u.NOME_ALUNO from reconhecimento as r inner join unijui as u on u.matr_aluno = r.rg_aluno where r.ativo = 2 group by u.NOME_ALUNO ;";
	}
	}
	

                
                // Executa consulta SQL
                $query = mysql_query($sql);
                // Enquanto houverem registros no banco de dados
                while($row = mysql_fetch_array($query)) {
                   echo "<tr id=\"".$row['id']."\">";
                  echo "<td style=\"text-align: left; vertical-align: middle;\" scope=\"row\" class=\"w-25\"> <img style=\"width: 80%; height: auto;\" src=\"../".$row['imagem']."\" class=\"img-fluid img-thumbnail\" alt=\"Sheep\"></td>";
                  echo "<td style=\"text-align: left; vertical-align: middle;\" scope=\"row\" class=\"w-25\">".$row['NOME_ALUNO']."</td>";
                 echo "<td style=\"text-align: left; vertical-align: middle;\" scope=\"row\" class=\"w-25\">".$row['rg_aluno']."</td>";
?>
                  <td style="text-align: left; vertical-align: middle;">
                    <div class="text-center">
                      <a href="dash.php?id=<?php echo $row['id'] ?>&op=1"><i class="fas fa-user-check" style="padding-right: 20%; color: black"></i></a>
                      <a href="dash.php?id=<?php echo $row['id'] ?>&op=2"><i class="fas fa-user-times"  style="color: black"></i></a>
                    </div>
                    
                  </td>
<?php

                  echo "</tr>";
                }
                ?>

		  </tbody>
		</table>   
    </div>
  </div>
</div>

<script type="text/javascript">
	$( document ).ready(function() {
    $("#pesquisarButton").click( function(){
    	location.href="dash.php?filter="+$('#cad :selected').val();
           }
      );
});
</script>

</body>
</html>
